modules:
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Snapshot
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.baobab
        - org.gnome.SimpleScan
        - org.gnome.Evince
        - com.mattjakeman.ExtensionManager
        - org.gnome.font-viewer
        - org.gnome.Loupe
        - org.gnome.Logs
        - org.gnome.Maps
        - org.gnome.Photos
        - org.gnome.NautilusPreviewer
        - org.gnome.TextEditor
        - org.gnome.Totem
        - org.gnome.Weather
        - com.raggesilver.BlackBox
        - ca.desrt.dconf-editor
      
