# image will be published to ghcr.io/<user>/<name>
name: silverblue-main
# description will be included in the image's metadata
description: Custom Silverblue image based on UBlue-OS.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/prompt/repo/fedora-%OS_VERSION%/kylegospo-prompt-fedora-%OS_VERSION%.repo
    install:
      - ptyxis
      - neovim
      - starship
      - just
      - distrobox
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - from-file: flatpaks/gnome-flatpaks.yml

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.mozilla.Thunderbird
        - it.mijorus.gearlever
        - org.kicad.KiCad
        - org.gnome.Boxes
        # - org.DolphinEmu.dolphin-emu
        - com.github.flxzt.rnote
        - com.obsproject.Studio
        - org.videolan.VLC
        - org.inkscape.Inkscape
        - org.blender.Blender
        - org.kde.krita
        - org.gimp.GIMP
        - org.libreoffice.LibreOffice
        - com.github.tchx84.Flatseal
        - com.usebottles.bottles
        - io.missioncenter.MissionCenter
        - io.github.flattool.Warehouse
        - com.discordapp.Discord
        - org.libretro.RetroArch
        - net.lutris.Lutris
        - com.valvesoftware.Steam
        - io.podman_desktop.PodmanDesktop
        - io.github.celluloid_player.Celluloid
        - cc.arduino.IDE2
        - io.github.dvlv.boxbuddyrs
        - org.godotengine.Godot
        - com.prusa3d.PrusaSlicer
        - com.github.GradienceTeam.Gradience
        - fm.reaper.Reaper
        - org.pipewire.Helvum
        - page.codeberg.libre_menu_editor.LibreMenuEditor
        - de.philippun1.turtle
        # - org.famistudio.FamiStudio # NES music editor

      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

