# image will be published to ghcr.io/<user>/<name>
name: silverblue-legion
# description will be included in the image's metadata
description: Custom Silverblue image based on UBlue-OS.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: packages/common-rpms.yml
  - from-file: packages/gnome-flatpaks.yml
  

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

