# image will be published to ghcr.io/<user>/<name>
name: silverblue-framework
# description will be included in the image's metadata
description: Custom Silverblue image based on UBlue-OS.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - from-file: packages/gnome-flatpaks.yml
  - from-file: packages/common-rpms.yml
  - type: script
    snippets: 
    - "curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm"

  - type: rpm-ostree
    remove:
      - nvtop

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

